-- MySQL Script generated by MySQL Workbench
-- Mon Oct 30 22:12:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BNotas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BNotas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BNotas` DEFAULT CHARACTER SET utf8 ;
USE `BNotas` ;

-- -----------------------------------------------------
-- Table `BNotas`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BNotas`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BNotas`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BNotas`.`Notas` (
  `idNota` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `conteudo` VARCHAR(500) NOT NULL,
  `cor` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idNota`),
  INDEX `fk_Notas_Usuarios_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Notas_Usuarios`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `BNotas`.`Usuarios` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into usuarios values(1, "Admin", "admin@admin.com", "admin", 2);